version: "3"
services:
  transeptor-bundler:
    container_name: transeptor-bundler
    image: transeptorlabs/bundler:latest
    ports:
      - "4337:4337"
    env_file:
      - ./.env
    command: >
      --port 4337
      --network http://host.docker.internal:8545
      --txMode base
      --httpApi web3,eth,debug